# Generated by Django 2.2.24 on 2022-09-20 14:46
import phonenumbers
from django.db import migrations


def set_building_is_new(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Flat.objects.all().update(new_building=F('construction_year') >= 2015)


def get_correct_number(apps, schema_editor):
    def parse_number(raw_number):
        parsed_number = phonenumbers.parse(
                raw_number,
                'RU'
            )
        if phonenumbers.is_valid_number(parsed_number):
            return parsed_number

    Flat = apps.get_model('property', 'Flat')
    Flat.objects.update(
        owner_pure_phone=parse_number(
            F(
                'owners_phonenumber'
                )
            )
        )


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(set_building_is_new),
        migrations.RunPython(get_correct_number),
        migrations.DeleteModel(
            name='Owner',
        ),
    ]
