# Generated by Django 2.2.24 on 2022-09-20 14:51

from django.db import migrations

def transfer_owners(apps, schema_editor):
    Flats = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    owners =Owner.objects.all()
    flats_all = Flats.objects.all()
    for flat in flats_all:
        owners.get_or_create(
            Owner_name=flat.owner,
            owner_phonenumber=flat.owners_phonenumber,
            owner_pure_phone=flat.owner_pure_phone
        )


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_owner'),
    ]

    operations = [
        migrations.RunPython(transfer_owners)
    ]
