# Generated by Django 2.2.24 on 2022-09-20 14:51

from django.db import migrations


def transfer_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    owners = Owner.objects.all()
    if owners.exists():
        for owner in owners.interator():
            flats = Flat.objects.filter(
                owner=owner.name,
                owner_pure_phone=owner.pure_phone
            )
            if flats:
                owner.flats.set(flats)


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0003_owner'),
    ]

    operations = [
        migrations.RunPython(transfer_owners)
    ]
